repos:
  - repo: https://github.com/python/black
    rev: 21.9b0
    hooks:
      - id: black
  - repo: https://github.com/hadialqattan/pycln
    rev: v1.0.3
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]
